from __future__ import annotations

from ombrebrain.architecture.contracts import ComponentDescriptor, ComponentGraph, SideEffectMode


def default_architecture() -> ComponentGraph:
    return ComponentGraph(
        (
            ComponentDescriptor(
                name="protocol.schemas",
                layer="protocol",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                owns_surfaces=("event_schema",),
                critical=True,
            ),
            ComponentDescriptor(
                name="domain.commands",
                layer="domain",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("protocol.schemas",),
                owns_surfaces=("command_plan",),
                critical=True,
            ),
            ComponentDescriptor(
                name="app.execution",
                layer="app",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("protocol.schemas",),
                critical=True,
            ),
            ComponentDescriptor(
                name="app.command_bridge",
                layer="app",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("domain.commands", "app.execution"),
                owns_surfaces=("legacy_command_mapping",),
                critical=True,
            ),
            ComponentDescriptor(
                name="fabric.memory_fabric",
                layer="fabric",
                side_effect_mode=SideEffectMode.WRITE_SIDE_CHANNEL,
                dependencies=("protocol.schemas",),
                owns_surfaces=("v3_wal", "memory_fabric"),
                critical=True,
            ),
            ComponentDescriptor(
                name="projection.audit_runtime",
                layer="projection",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("domain.commands",),
                owns_surfaces=("projection_journal", "projection_observations", "consistency_report"),
                critical=True,
            ),
            ComponentDescriptor(
                name="policy.engine",
                layer="policy",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("domain.commands", "app.execution"),
                owns_surfaces=("policy_verdict", "capability_contract"),
                critical=True,
            ),
            ComponentDescriptor(
                name="decision.ledger",
                layer="decision",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("projection.audit_runtime", "policy.engine"),
                owns_surfaces=("decision_record",),
                critical=True,
            ),
            ComponentDescriptor(
                name="decision.debug",
                layer="decision",
                side_effect_mode=SideEffectMode.READ_ONLY,
                dependencies=("decision.ledger", "fabric.memory_fabric"),
                critical=True,
            ),
            ComponentDescriptor(
                name="acceptance.harness",
                layer="acceptance",
                side_effect_mode=SideEffectMode.READ_ONLY,
                critical=True,
            ),
            ComponentDescriptor(
                name="eventsourcing.kernel",
                layer="eventsourcing",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("domain.commands", "protocol.schemas"),
                owns_surfaces=("event_sourced_metadata",),
                critical=True,
            ),
            ComponentDescriptor(
                name="retrieval.engine",
                layer="retrieval",
                side_effect_mode=SideEffectMode.READ_ONLY,
                dependencies=("domain.commands",),
                critical=True,
            ),
            ComponentDescriptor(
                name="microkernel.runtime",
                layer="microkernel",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("policy.engine",),
                owns_surfaces=("capability_microkernel_decision",),
                critical=True,
            ),
            ComponentDescriptor(
                name="plugins.runtime",
                layer="plugins",
                side_effect_mode=SideEffectMode.AUDIT_ONLY,
                dependencies=("microkernel.runtime",),
                owns_surfaces=("plugin_sandbox_decision",),
                critical=True,
            ),
            ComponentDescriptor(
                name="distributed.coordinator",
                layer="distributed",
                side_effect_mode=SideEffectMode.WRITE_SIDE_CHANNEL,
                dependencies=("fabric.memory_fabric",),
                owns_surfaces=("distributed_fabric",),
                critical=True,
            ),
            ComponentDescriptor(
                name="app.legacy_runtime",
                layer="app",
                side_effect_mode=SideEffectMode.WRITE_SIDE_CHANNEL,
                dependencies=(
                    "app.execution",
                    "app.command_bridge",
                    "fabric.memory_fabric",
                    "projection.audit_runtime",
                    "policy.engine",
                    "decision.ledger",
                    "eventsourcing.kernel",
                    "retrieval.engine",
                    "microkernel.runtime",
                ),
                owns_surfaces=("v3_trace_metadata",),
                critical=True,
            ),
            ComponentDescriptor(
                name="web.v3_debug",
                layer="web",
                side_effect_mode=SideEffectMode.READ_ONLY,
                dependencies=("decision.debug", "app.legacy_runtime"),
                critical=True,
            ),
            ComponentDescriptor(
                name="frontend.dashboard.v3_debug",
                layer="frontend",
                side_effect_mode=SideEffectMode.READ_ONLY,
                dependencies=("web.v3_debug",),
                critical=True,
            ),
        )
    )
